## Numpy array and basics



In [1]:
import numpy as np

### creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)




1D array:  [1 2 3 4 5]


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [7]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 3)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 3)





Python list multiplication  [1, 2, 3, 1, 2, 3, 1, 2, 3]
Python array multiplication  [3 6 9]


In [8]:
pip install time

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement time
ERROR: No matching distribution found for time


In [9]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)



Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.17075300216674805

 Numpy operation time:  0.005986213684082031


# creating array from scratch

In [4]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
ones = np.ones((2, 3))
print("one array: \n", ones)

one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
full = np.full((2, 2), 8)
print("full array: \n", full)


full array: 
 [[8 8]
 [8 8]]


In [7]:
random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 21, 2)
print("sequnce array: \n", sequence)

random array: 
 [[0.25579723 0.45084083 0.85404273]
 [0.47366794 0.94920791 0.7562241 ]]
sequnce array: 
 [ 0  2  4  6  8 10 12 14 16 18 20]


### Vector, Matrix and Tensor

In [19]:
vector = np.array([1, 2, 3])  #1DIMENSIONAL
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], #2DIMENSIONAL
                   [4, 5, 6]])
print("Matrix: ", matrix)


tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]]) # MULTI DIMENSIONAL
print("Tensor: ", tensor)





Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [20]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int32


### Array Reshaping

In [23]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)


Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)



 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
